### ISSUE TITLE
hover effect bug.

### ISSUE THREAD

**Issue by KParthSingh** [RikisuT/Youtube-Fluent-Theme#10]
https://github.com/RikisuT/Youtube-Fluent-Theme/assets/99123839/cacd1eb2-54e9-44f9-9e82-758ce0b0f832

until click on some were on the page the hover effect does not work.

**Comment by KParthSingh** [comment]
also can you make the notification section bit more dark? the text is hard to see
![Screenshot 2024-02-24 105407](https://github.com/RikisuT/Youtube-Fluent-Theme/assets/99123839/6c5418d5-5dcf-41b9-9676-397a56e45b87)
thanks

**Comment by RikisuT** [comment]
```css
 #contentWrapper.tp-yt-iron-dropdown > *{
   min-width: fit-content;
   background-color: #00000042 !important;
}
```
fix for the notif panel
find the selector for which the bg color is set then change it. Here it is "#contentWrapper.tp-yt-iron-dropdown > *" line
