### ISSUE TITLE
Missing Features

### ISSUE THREAD

**Issue by SadaydZ** [RikisuT/Youtube-Fluent-Theme#8]
Unfortunately it's not working at all, again.

Windows Caption Blur is enabled but doesn't seem to work properly, same with sidebar and return-youtube-dislike

**Captions and YouTube Dislike**
![Captions and YT Dislike](https://github.com/RikisuT/Youtube-Fluent-Theme/assets/85256569/fbfce6d6-72dd-4176-920e-c35bdd785fef)

**Sidebar**
![Sidebar](https://github.com/RikisuT/Youtube-Fluent-Theme/assets/85256569/066c2ed3-98c6-4cb5-b2ec-c7dfe136b9e9)

**Comment by RikisuT** [comment]
Youtube dislike wont work directly from the extension as we enable the old desc and remove the new one.
Due to this we will have 2 desc and RYD applies to the first. To work around this I have used the js version of the extension, which we can import into Tampermonkey.
[Link to the issue where I have sent the currently working solution](https://github.com/Anarios/return-youtube-dislike/issues/920#issuecomment-1642531798)
About the comments I have left the background as it is just because of the many custom themes that Youtube videos have nowadays. You can manually set the background transparency to be 0% in the caption settings. It will apply for all the videos played from that browser, unless you clear the cache
Sidebar is a different issue personally I didn't like it that much so I removed the whole page blur 
Looking back it seems as if I should've done that to the code pasted here too.
You can use [the code I'm currently using](https://github.com/RikisuT/Youtube-Fluent-Theme/blob/main/Themes/personal-backup.css) to overcome the sidebar issue.
My personal code also has the fix for RYD alignment.

**Comment by RikisuT** [comment]
Sorry for being late, I have no excuses this time. I just forgot to open Github.

**Comment by SadaydZ** [comment]
With the solution of manually setting the transparency to 0%, the blur works perfectly in the captions, the sidebar still appears exactly the same as the 2nd image I sent. RYD works with the Tampermonkey script version as you said.

**Comment by RikisuT** [comment]
Again sorry for being late. Removing these lines of code from the CSS code should help
Removing the first part should do the job
2nd part extends the sidebar area such that the 3rd part of the code can darken the screen when the sidebar is opened.

```css
 div#scrim, #scrim.tp-yt-app-drawer {
     transition-property: opacity, backdrop-filter !important;
     transition-duration: 200ms !important;
     transition-timing-function: cubic-bezier(0, .8, .2, 1) !important;
     backdrop-filter: blur(5px) !important;
}
 tp-yt-app-drawer#guide {
     width: auto !important;
     right: 0 !important;
     transition-property: visibility !important;
     transition-duration: 200ms !important;
}

 tp-yt-app-drawer#guide[opened][reveal-nav-bar] #scrim.tp-yt-app-drawer {
     opacity: 1 !important;
}
```
